services:
  php:
    build: ./tools/ci
    container_name: saml-value-object-php
    working_dir: /app
    tty: true
    stdin_open: true
    command: bash -lc "tail -f /dev/null"
    volumes:
      - ./:/app
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      COMPOSER_HOME: /app/.composer

